version: '3'

services:
  giadog:
    build: /home/pi/giadog
    volumes:
      - ./:/catkin_ws/src/giadog/
    network_mode: "host"
    devices:
      - /dev/i2c-1:/dev/i2c-1
      # - /dev/input/js0:/dev/input/js0